on: [push]

name: CI

jobs:
  build:
    name: pactlers
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - name: Install udev
        run: sudo apt-get update && sudo apt-get install -y libudev-dev
      - name: pactlers
        run: cargo check
        working-directory: ./pactlers
  build-fw:
    name: pactlers
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: thumbv7m-none-eabi
      - name: pactlers-fw
        run: cargo check
        working-directory: ./pactlers-fw
